/**
 *  Copyright (C) 2021 - Innovusion Inc.
 *
 *  All Rights Reserved.
 *
 *  $Id$
 */

#ifndef SDK_COMMON_INNO_FAULTS_ROBINE2_H_
#define SDK_COMMON_INNO_FAULTS_ROBINE2_H_

/*RobinE2X fault list*/
enum InnoLidarRobinE2XInFault {
  INNO_LIDAR_ROBINE2X_IN_FAULT_OTHER = 0,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POWER_LOW = 1,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POWER_HIGH = 2,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MCUVREF = 3,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POWSUP2 = 4,
  INNO_LIDAR_ROBINE2X_IN_FAULT_LASER5V = 5,
  INNO_LIDAR_ROBINE2X_IN_FAULT_LASER_SWITCH_STUCK_CLOSE = 6,
  INNO_LIDAR_ROBINE2X_IN_FAULT_PMIC = 7,
  INNO_LIDAR_ROBINE2X_IN_FAULT_LASER_INTERLOCK = 8,
  INNO_LIDAR_ROBINE2X_IN_FAULT_FPGA_CONFIG = 9,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_SPEEDLOW = 10,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MIPIERROR_FPGA = 11,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MIPITIMEOUT_FPGA = 12,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MIPIERROR_SOC = 13,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MIPITIMEOUT_SOC = 14,
  INNO_LIDAR_ROBINE2X_IN_FAULT_COM_PMIC_TIMEOUT = 15,
  INNO_LIDAR_ROBINE2X_IN_FAULT_COM_PMIC_CRC = 16,
  INNO_LIDAR_ROBINE2X_IN_FAULT_WB = 17,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_SENSOR_PLAUSIBILITY = 18,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_HALL = 19,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_CONTROL = 20,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_STUCK = 21,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_PREDRIVE = 22,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_OC = 23,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_OVERDRIVE = 24,
  INNO_LIDAR_ROBINE2X_IN_FAULT_VBIAS = 25,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SPAD_CONFIG = 26,
  INNO_LIDAR_ROBINE2X_IN_FAULT_EPHY = 27,
  INNO_LIDAR_ROBINE2X_IN_FAULT_DBTEMP = 28,
  INNO_LIDAR_ROBINE2X_IN_FAULT_COM_LPDDR = 29,
  INNO_LIDAR_ROBINE2X_IN_FAULT_FLASH_FILE = 30,
  INNO_LIDAR_ROBINE2X_IN_FAULT_PTP_TIMEOUT = 31,
  INNO_LIDAR_ROBINE2X_IN_FAULT_FLASH = 32,
  INNO_LIDAR_ROBINE2X_IN_FAULT_PTPOFFSET = 33,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MOTORSYN_FAULT = 34,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SOC_EXTWD = 35,
  INNO_LIDAR_ROBINE2X_IN_FAULT_COM_MCU_TIMEOUT = 36,
  INNO_LIDAR_ROBINE2X_IN_FAULT_COM_MCU_CHECKSUM = 37,
  INNO_LIDAR_ROBINE2X_IN_FAULT_FPGA_SEU = 38,
  INNO_LIDAR_ROBINE2X_IN_FAULT_LASER_OVERHEAT1 = 39,
  INNO_LIDAR_ROBINE2X_IN_FAULT_PROTECTION = 40,
  INNO_LIDAR_ROBINE2X_IN_FAULT_FPGA_OVERHEAT = 41,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SOC_OVERHEAT = 42,
  INNO_LIDAR_ROBINE2X_IN_FAULT_FPGA_CDONE = 43,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SOC = 44,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SOC_BUSTIMEOUT = 45,
  INNO_LIDAR_ROBINE2X_IN_FAULT_ETHERNET1 = 46,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SPAD = 47,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SOCCLOCK = 48,
  INNO_LIDAR_ROBINE2X_IN_FAULT_APU_WD = 49,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SPAD_LATENT = 50,
  INNO_LIDAR_ROBINE2X_IN_FAULT_ASSERT_FAILURE = 51,
  INNO_LIDAR_ROBINE2X_IN_FAULT_CPULOAD_HIGH = 52,
  INNO_LIDAR_ROBINE2X_IN_FAULT_LATENCY_LONG = 53,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MIPISTUCK = 54,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SPAD_READYNOK = 55,
  INNO_LIDAR_ROBINE2X_IN_FAULT_TRIGGER = 56,
  INNO_LIDAR_ROBINE2X_IN_FAULT_EXCESSIVE_NOISE = 57,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MODE_ENTER = 58,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SCATTER_INTENSITY = 59,
  INNO_LIDAR_ROBINE2X_IN_FAULT_POLYGON_CROSSCHECK = 60,
  INNO_LIDAR_ROBINE2X_IN_FAULT_DATA_DROP5 = 61,
  INNO_LIDAR_ROBINE2X_IN_FAULT_ETH_SQI = 62,
  INNO_LIDAR_ROBINE2X_IN_FAULT_ETH_FRAMEDROP = 63,
  INNO_LIDAR_ROBINE2X_IN_FAULT_ETH_FCSERROR = 64,
  INNO_LIDAR_ROBINE2X_IN_FAULT_ETH_E2E = 65,
  INNO_LIDAR_ROBINE2X_IN_FAULT_SPI0_CHECKSUM = 66,
  INNO_LIDAR_ROBINE2X_IN_FAULT_MAX,
};

#endif  // SDK_COMMON_INNO_FAULTS_ROBINE2_H_
